- server/src/main/kotlin/org/tod87et/roomkn/server/database/Db.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/Entries.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/Schema.kt
> Add database

- server/build.gradle.kts
- server/src/main/kotlin/org/tod87et/roomkn/server/database/Db.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/Entries.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/LoginUserInfo.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/Reservation.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/RoomInfo.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/ShortRoomInfo.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/ShortUserInfo.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/UnregisteredReservation.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/UnregisteredUserInfo.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/UserInfo.kt
Убрал Entries и добавил все models из вики
> Remove Entries, add Models

- server/src/main/kotlin/org/tod87et/roomkn/server/database/CredentialsDatabase.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseFactory.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/LoginUserInfo.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/RegistrationUserInfo.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/UnregisteredUserInfo.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/UserCredentialsInfo.kt
> #68: Database api v2

- server/src/main/kotlin/org/tod87et/roomkn/server/routing/ApiRouting.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/Reserve.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
resolves #8 
resolves #17
resolves #18
resolves #19
resolves #20
> Routes: minimal API functioanality

- .github/workflows/server-test-action.yml
Resolves https://github.com/spbu-math-cs/roomkn/issues/104
> Added path filter for PR

- server/src/main/kotlin/org/tod87et/roomkn/server/Application.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/auth/AccountController.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/auth/AccountControllerImpl.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/auth/AuthConfig.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/auth/AuthConfigFactory.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/auth/AuthSession.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/plugins/Authentication.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/plugins/CleanupThreads.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/plugins/Routing.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/AccountRouting.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/ApiRouting.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/AuthTest.kt
> Add logout routing

- client/src/api/FakeAPI.js
- client/src/components/Content.css
- client/src/pages/Room.css
- client/src/pages/Room.js
Изменение интерфейса, теперь name в резервации связан с контекстом авторизации (если пользователь авторизован, использует его имя, иначе не дает ничего забронировать).
> use auth context for reservations

- server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/AuthTest.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/ConnectionTest.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/KtorTestEnv.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/RoomsRoutesTests.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/UsersRoutesTests.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/models/Conversations.kt
> Room admin API

- client/src/pages/Room.js
- server/src/main/kotlin/org/tod87et/roomkn/server/models/reservations/ReservationRequest.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/reservations/UnregisteredReservation.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/Reserve.kt
> Remove user_id in /reserve

- client/src/pages/admin/AdminRoomList.js
- client/src/pages/admin/AdminUserList.js
updates to the new API; without this admin requests just aren't working. pls approve
> update admin routing

- client/src/api/API.js
- client/src/pages/Room.css
- client/src/pages/Room.js
- client/src/pages/UserReservation.css
- client/src/pages/UserReservation.js
> Added delete button

- server/build.gradle.kts
- server/src/main/kotlin/org/tod87et/roomkn/server/Application.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/auth/AccountControllerImpl.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/auth/AuthConfig.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/auth/AuthSession.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/plugins/CallLogging.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/plugins/Logging.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReservationsRouting.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/UsersRouting.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/defaultResponses.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/UsersRoutesTests.kt
> Remove permissions from cookie

- server/src/main/kotlin/org/tod87et/roomkn/server/auth/AccountControllerImpl.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/CredentialsDatabase.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/Schema.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/DiTest.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/database/DatabaseTest.kt
> Active tokens

- client/src/components/Navbar.js
> Move MyReservations link to right and hide for unauthorized

- client/src/api/API.js
- client/src/api/FakeAPI.js
- client/src/components/Auth.js
- client/src/pages/List.js
- client/src/pages/Profile.js
- client/src/pages/Room.js
- client/src/pages/SignIn.js
- client/src/pages/SignUp.js
- client/src/pages/UserReservation.js
- client/src/pages/admin/AdminRoomList.js
- client/src/pages/admin/AdminUserList.js
осталась админка, здесь в SignUp какие-то траблы, работает через раз
еще пофикшу
> rewrite stateful api to callback api

- server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReservationsRouting.kt
> Handle ReservationException

- server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/users/FullUserInfo.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/UsersRouting.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/DiTest.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/KtorTestEnv.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/UsersRoutesTests.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/database/DatabaseTest.kt
> Permission list in GET /users

- server/docs/api/openapi-release-0.0.1.yaml
- server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/rooms/NewRoomInfoWithNull.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/users/UpdateUserInfoWithNull.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/UsersRouting.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/util/DefaultResultHandler.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/DiTest.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/RoomsRoutesTests.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/UsersRoutesTests.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/models/Conversations.kt
В процессе был один merge из main, но он был простой
> Partial PUT (PATCH)

- client/src/App.js
- client/src/components/Navbar.js
- client/src/components/SnackbarAlert.js
- client/src/pages/Profile.js
- client/src/pages/Room.js
- client/src/pages/SignIn.js
- client/src/pages/SignUp.js
- client/src/pages/UserReservation.js
> Replace alerts to snackbars

- server/docs/api/openapi-release-0.0.1.yaml
- server/src/main/kotlin/org/tod87et/roomkn/server/Application.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/Schema.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/plugins/defaultMapCreation.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/DiTest.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/RoomsRoutesTests.kt
> Map in server

- client/src/components/TimelineForRoomList.css
- client/src/components/TimelineForRoomList.js
- client/src/pages/List.js
- client/src/pages/Room.js
> Timeline in room list

- server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/RoomsRoutesTests.kt
> Remove auth for get /map

- server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
> Fix missing element status code & db

- server/build.gradle.kts
- server/gradle.properties
- server/src/main/kotlin/org/tod87et/roomkn/server/Application.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/plugins/Metrics.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/MetricsTest.kt
> Add kTor metrics

- server/src/main/kotlin/org/tod87et/roomkn/server/models/reservations/NewReservationBounds.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReservationsRouting.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/ReservationsRoutesTests.kt
> Add update reservation support

- server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReservationsRouting.kt
> Check permission on reservation create

- client/src/App.js
- client/src/api/FakeAPI.js
- client/src/components/AdminWrapper.js
- client/src/components/Auth.js
- client/src/pages/admin/AdminPanel.js
- client/src/pages/admin/AdminUserList.js
Не прячим ссылку на админскую панел, так как navbar поменяется в другом моём PR
> Current user permissions and redirect from AdminPanel

- server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReservationsRouting.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/ReservationsRoutesTests.kt
> Handle serialization exception

- client/src/components/SnackbarAlert.js
Пофиксил неотображающиеся сообщения
> Fix snackbar

- client/src/pages/List.js
> Added buttons in room list

- server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/defaultResponses.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/room.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/DiTest.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/RoomsRoutesTests.kt
> Add /rooms/list-short

- server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/reservations/Reservation.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/KtorTestEnv.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/ReservationsRoutesTests.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/database/DatabaseTest.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/models/Conversations.kt
> Extend Reservation structure

- server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/reservations/FailedReservation.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/reservations/MultipleReservationResult.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReservationsRouting.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/ReservationsRoutesTests.kt
> Add /reserve/multiple

- client/src/api/API.js
- client/src/pages/List.js
- client/src/pages/Room.js
> Repeated reservations

- client/src/pages/Profile.js
Добавил базовую смену пароля в профайле
> add password change

- client/src/pages/admin/AdminReservations.js
- client/src/pages/admin/AdminRoomList.js
- client/src/pages/admin/AdminUserList.js
> add snackbars in admin panel

- server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/reservations/ReservationSortParameter.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/ReservationsRouting.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/DiTest.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/ReservationsRoutesTests.kt
> Add order parameters to GET /reservations

- client/src/pages/Map.js
> Add room name queries in map 

- client/src/pages/admin/AdminReservations.js
> Fixed sort by in admin reservation list

- client/src/pages/admin/AdminUserList.js
> Fix admin user permissions show

- server/src/main/kotlin/org/tod87et/roomkn/server/Application.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/plugins/Cors.kt
- server/src/main/resources/dev.conf
> Disable cors in prod

- client/src/App.js
- client/src/components/Auth.js
- client/src/components/Footer.js
- client/src/pages/Room.js
wwww|aaaa|qqqqq
------------------|------------------|---------------
> Mobile buttoms

- server/src/main/kotlin/org/tod87et/roomkn/server/database/Database.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/DatabaseSession.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/database/Schema.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/users/InviteRequest.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/users/SaltedInvite.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/models/users/SaltedInviteRequest.kt
- server/src/main/kotlin/org/tod87et/roomkn/server/routing/UsersRouting.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/DiTest.kt
- server/src/test/kotlin/org/tod87et/roomkn/server/UsersRoutesTests.kt
> Add salt to invite token
